### ISSUE TITLE
Preverjanje povezanosti

### ISSUE THREAD

**Issue by evadezelak** [nejclu/Eccentricity-Closeness-BetweennessCentrality#2]
Spoštovani, 
pri pisanju definicije za algoritem se nama je pojavila težava pri generiranju novih grafov za preverjanje povezanosti grafa, saj v primeru, da graf ni povezan, se pojavlja težava pri računanju bližine, kjer potem pride do deljenja z 0. Zanima me, če morda obstaja kakšna funkcija, s katero se da preveriti, če je graf povezan v Sage-u?

Hvala in lep pozdrav, 
Eva Deželak

**Comment by jaanos** [comment]
Povezanost grafa `G` lahko preverita z `G.is_connected()`.
