### ISSUE TITLE
Socialno omrežje

### ISSUE THREAD

**Issue by nejclu** [nejclu/Eccentricity-Closeness-BetweennessCentrality#3]
Spoštovani,
na repozitorij sva naložila primer socialnega omrežja (```facebook_combined.txt```) in ga uvozila v Sage (```socialno_omrezje.ipynb```). Zanj sva poskušala izračunati vrednosti vseh treh mer, a nama javlja napako. (Vzrok napake: ```AttributeError: 'Graph' object has no attribute 'distance_all_pairs'```). Je ta format/tip datoteke primeren ali bi bilo bolje najti podatke v kakšni drugi obliki?

Hvala in lep pozdrav,
Nejc Lukežič

**Comment by jaanos** [comment]
Trenutno graf prebereta v obliko `networkx`. Kot Sage-ov graf ga lahko prebereta z
```sage
with open("facebook_combined.txt") as f:
    G = Graph([tuple(int(u) for u in l.split()) for l in f.readlines()])
```
Lahko pa tudi že prebrani graf v obliki `networkx` pretvorita v Sage-ov graf, npr.
```sage
G_sage = Graph(G_fb)
```
Na Sage-ovem grafu lahko potem uporabita metodo `distance_all_pairs` (in druge).

**Comment by nejclu** [comment]
Spoštovani,
poskušala sva socialno omrežje pretvoriti v Sage-ov graf, a uporaba metode ```distance_all_pairs``` na njih še vedno javi napako. Prav tako nama javi napako, če poskušava metodo uporabiti na podgrafu Sage-ovega grafa (podgraf pridobljen s funkcijo ```G.random_subgraph()```). V obeh primerih dobiva napako oblike ```KeyError:``` za katero stoji številka.

Hvala in lep pozdrav,
Nejc Lukežič
